CREATE DATABASE retropanda;
USE retropanda;

CREATE TABLE EMPRESA (
	ID_EMPRESA SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	NOMBRE_EMPRESA VARCHAR(30) NOT NULL,
	PAIS VARCHAR(50) NOT NULL
);

CREATE TABLE DESARROLLADORA (
	ID_DESARROLLADORA SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	ID_EMPRESA SMALLINT(5) UNSIGNED,
	
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE DISTRIBUIDORA (
	ID_DISTRIBUIDORA SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	ID_EMPRESA SMALLINT(5) UNSIGNED,
	
	FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE PLATAFORMA (
	ID_PLATAFORMA SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	REGION VARCHAR(50) NOT NULL
);

CREATE TABLE JUEGO (
	ID_JUEGO SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	GENERO1 ENUM ('ACCION','SHOOTER','ESTRATEGIA','SIMULACION','DEPORTES','CARRERAS','AVENTURAS','ROL'),
	GENERO2 ENUM ('ACCION','SHOOTER','ESTRATEGIA','SIMULACION','DEPORTES','CARRERAS','AVENTURAS','ROL'),
	GENERO3 ENUM ('ACCION','SHOOTER','ESTRATEGIA','SIMULACION','DEPORTES','CARRERAS','AVENTURAS','ROL'),
	GENERO4 ENUM ('ACCION','SHOOTER','ESTRATEGIA','SIMULACION','DEPORTES','CARRERAS','AVENTURAS','ROL'),
	FECHA_PUBLICACION DATE NOT NULL,
	REGION1 VARCHAR(50),
	REGION2 VARCHAR(50),
	REGION3 VARCHAR(50),
	REGION4 VARCHAR(50),
	CARATULA VARCHAR(30) NOT NULL,
	ID_DESARROLLADORA SMALLINT(5) UNSIGNED NOT NULL,
	
	FOREIGN KEY (ID_DESARROLLADORA) REFERENCES DESARROLLADORA(ID_DESARROLLADORA)
);

CREATE TABLE USUARIO (
	ID_USUARIO SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	EMAIL VARCHAR (30) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	CONTRASEÑA VARCHAR(40) NOT NULL,
	IMAGEN_PERFIL VARCHAR (200) NOT NULL,
	BIOGRAFIA VARCHAR (100) NOT NULL
);

CREATE TABLE PLATAFORMA_JUEGO (
	ID_JUEGO SMALLINT(5) UNSIGNED NOT NULL,
	ID_PLATAFORMA SMALLINT(5) UNSIGNED NOT NULL,
	
	FOREIGN KEY (ID_PLATAFORMA) REFERENCES PLATAFORMA(ID_PLATAFORMA),
	FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO)
);

CREATE TABLE JUEGO_USUARIO_COMPRADO (
	ID_JUEGO SMALLINT(5) UNSIGNED NOT NULL,
	ID_USUARIO SMALLINT(5) UNSIGNED NOT NULL,
	
	FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE JUEGO_USUARIO_WISHLIST (
	ID_JUEGO SMALLINT(5) UNSIGNED NOT NULL,
	ID_USUARIO SMALLINT(5) UNSIGNED NOT NULL,

	FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE VALORACION_JUEGO_USUARIO (
	ID_JUEGO SMALLINT(5) UNSIGNED NOT NULL,
	ID_USUARIO SMALLINT(5) UNSIGNED NOT NULL,
	VALORACION VARCHAR (50) NOT NULL,
	
	FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	
);

CREATE TABLE NOTICIAS (
	ID_NOTICIAS SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
	FECHA DATE NOT NULL
);

CREATE TABLE LANZAMIENTOS_PROXIMOS (
	ID_JUEGO SMALLINT(5) UNSIGNED NOT NULL,
	FECHA_LANZAMIENTOS DATE NOT NULL,
	
	FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO(ID_JUEGO)
);

